@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\Bundles.xnb" "%cd%\stardewvalley-xnb-files\yml\Bundles.yml"
@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\Bundles.es-ES.xnb" "%cd%\stardewvalley-xnb-files\yml\Bundles.es-ES.yml"
@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\Bundles.ja-JP.xnb" "%cd%\stardewvalley-xnb-files\yml\Bundles.ja-JP.yml"
@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\Bundles.pt-BR.xnb" "%cd%\stardewvalley-xnb-files\yml\Bundles.pt-BR.yml"
@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\Bundles.ru-RU.xnb" "%cd%\stardewvalley-xnb-files\yml\Bundles.ru-RU.yml"
@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\Bundles.de-DE.xnb" "%cd%\stardewvalley-xnb-files\yml\Bundles.de-DE.yml"
@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\Bundles.zh-CN.xnb" "%cd%\stardewvalley-xnb-files\yml\Bundles.zh-CN.yml"

@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\Bundles.hu-HU.xnb" "%cd%\stardewvalley-xnb-files\yml\Bundles.hu-HU.yml"
@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\Bundles.ko-KR.xnb" "%cd%\stardewvalley-xnb-files\yml\Bundles.ko-KR.yml"
@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\Bundles.it-IT.xnb" "%cd%\stardewvalley-xnb-files\yml\Bundles.it-IT.yml"
@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\Bundles.fr-FR.xnb" "%cd%\stardewvalley-xnb-files\yml\Bundles.fr-FR.yml"
@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\Bundles.tr-TR.xnb" "%cd%\stardewvalley-xnb-files\yml\Bundles.tr-TR.yml"

@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\CookingRecipes.xnb" "%cd%\stardewvalley-xnb-files\yml\CookingRecipes.yml"
@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\Furniture.xnb" "%cd%\stardewvalley-xnb-files\yml\Furniture.yml"
@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\hats.xnb" "%cd%\stardewvalley-xnb-files\yml\hats.yml"
@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\weapons.xnb" "%cd%\stardewvalley-xnb-files\yml\weapons.yml"
@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\ObjectInformation.xnb" "%cd%\stardewvalley-xnb-files\yml\ObjectInformation.yml"
@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\BigCraftablesInformation.xnb" "%cd%\stardewvalley-xnb-files\yml\BigCraftablesInformation.yml"
@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\Blueprints.xnb" "%cd%\stardewvalley-xnb-files\yml\Blueprints.yml"
@..\bin\xnbnode\node ..\bin\xnbnode\main.js  extract "%cd%\stardewvalley-xnb-files\CraftingRecipes.xnb" "%cd%\stardewvalley-xnb-files\yml\CraftingRecipes.yml"
