
xnbData: 
    target: "w"
    compressed: true
    hiDef: true
    readerData: 
        - 
            type: "Microsoft.Xna.Framework.Content.DictionaryReader`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]"
            version: 0

        - 
            type: "Microsoft.Xna.Framework.Content.StringReader"
            version: 0


    numSharedResources: 0

content:  #!Dictionary<String,String>
    Pantry/0: "{!! trim($spring->translation) !!}/{{$spring->prize->type}} {{$spring->prize->item->id}} {{$spring->prize->quantity}}/{{$spring->requirements[0]->item->id}} {{$spring->requirements[0]->quantity}} {{$spring->requirements[0]->quality->value}} {{$spring->requirements[1]->item->id}} {{$spring->requirements[1]->quantity}} {{$spring->requirements[1]->quality->value}} {{$spring->requirements[2]->item->id}} {{$spring->requirements[2]->quantity}} {{$spring->requirements[2]->quality->value}} {{$spring->requirements[3]->item->id}} {{$spring->requirements[3]->quantity}} {{$spring->requirements[3]->quality->value}}/0" #!String
    Pantry/1: "{!! trim($summer->translation) !!}/{{$summer->prize->type}} {{$summer->prize->item->id}} {{$summer->prize->quantity}}/{{$summer->requirements[0]->item->id}} {{$summer->requirements[0]->quantity}} {{$summer->requirements[0]->quality->value}} {{$summer->requirements[1]->item->id}} {{$summer->requirements[1]->quantity}} {{$summer->requirements[1]->quality->value}} {{$summer->requirements[2]->item->id}} {{$summer->requirements[2]->quantity}} {{$summer->requirements[2]->quality->value}} {{$summer->requirements[3]->item->id}} {{$summer->requirements[3]->quantity}} {{$summer->requirements[3]->quality->value}}/3" #!String
    Pantry/2: "{!! trim($fall->translation) !!}/{{$fall->prize->type}} {{$fall->prize->item->id}} {{$fall->prize->quantity}}/{{$fall->requirements[0]->item->id}} {{$fall->requirements[0]->quantity}} {{$fall->requirements[0]->quality->value}} {{$fall->requirements[1]->item->id}} {{$fall->requirements[1]->quantity}} {{$fall->requirements[1]->quality->value}} {{$fall->requirements[2]->item->id}} {{$fall->requirements[2]->quantity}} {{$fall->requirements[2]->quality->value}} {{$fall->requirements[3]->item->id}} {{$fall->requirements[3]->quantity}} {{$fall->requirements[3]->quality->value}}/2" #!String
    Pantry/3: "{!! trim($quality->translation) !!}/{{$quality->prize->type}} {{$quality->prize->item->id}} {{$quality->prize->quantity}}/{{$quality->requirements[0]->item->id}} {{$quality->requirements[0]->quantity}} {{$quality->requirements[0]->quality->value}} {{$quality->requirements[1]->item->id}} {{$quality->requirements[1]->quantity}} {{$quality->requirements[1]->quality->value}} {{$quality->requirements[2]->item->id}} {{$quality->requirements[2]->quantity}} {{$quality->requirements[2]->quality->value}} {{$quality->requirements[3]->item->id}} {{$quality->requirements[3]->quantity}} {{$quality->requirements[3]->quality->value}}/6/3" #!String
    Pantry/4: "{!! trim($animal->translation) !!}/{{$animal->prize->type}} {{$animal->prize->item->id}} {{$animal->prize->quantity}}/{{$animal->requirements[0]->item->id}} {{$animal->requirements[0]->quantity}} {{$animal->requirements[0]->quality->value}} {{$animal->requirements[1]->item->id}} {{$animal->requirements[1]->quantity}} {{$animal->requirements[1]->quality->value}} {{$animal->requirements[2]->item->id}} {{$animal->requirements[2]->quantity}} {{$animal->requirements[2]->quality->value}} {{$animal->requirements[3]->item->id}} {{$animal->requirements[3]->quantity}} {{$animal->requirements[3]->quality->value}} {{$animal->requirements[4]->item->id}} {{$animal->requirements[4]->quantity}} {{$animal->requirements[4]->quality->value}} {{$animal->requirements[5]->item->id}} {{$animal->requirements[5]->quantity}} {{$animal->requirements[5]->quality->value}} 639 1 0 640 1 0 641 1 0 642 1 0 643 1 0/4/5" #!String
    Pantry/5: "{!! trim($artisan->translation) !!}/{{$artisan->prize->type}} {{$artisan->prize->item->id}} {{$artisan->prize->quantity}}/{{$artisan->requirements[0]->item->id}} {{$artisan->requirements[0]->quantity}} {{$artisan->requirements[0]->quality->value}} {{$artisan->requirements[1]->item->id}} {{$artisan->requirements[1]->quantity}} {{$artisan->requirements[1]->quality->value}} {{$artisan->requirements[2]->item->id}} {{$artisan->requirements[2]->quantity}} {{$artisan->requirements[2]->quality->value}} {{$artisan->requirements[3]->item->id}} {{$artisan->requirements[3]->quantity}} {{$artisan->requirements[3]->quality->value}} {{$artisan->requirements[4]->item->id}} {{$artisan->requirements[4]->quantity}} {{$artisan->requirements[4]->quality->value}} {{$artisan->requirements[5]->item->id}} {{$artisan->requirements[5]->quantity}} {{$artisan->requirements[5]->quality->value}} {{$artisan->requirements[6]->item->id}} {{$artisan->requirements[6]->quantity}} {{$artisan->requirements[6]->quality->value}} {{$artisan->requirements[7]->item->id}} {{$artisan->requirements[7]->quantity}} {{$artisan->requirements[7]->quality->value}} {{$artisan->requirements[8]->item->id}} {{$artisan->requirements[8]->quantity}} {{$artisan->requirements[8]->quality->value}} {{$artisan->requirements[9]->item->id}} {{$artisan->requirements[9]->quantity}} {{$artisan->requirements[9]->quality->value}} {{$artisan->requirements[10]->item->id}} {{$artisan->requirements[10]->quantity}} {{$artisan->requirements[10]->quality->value}} {{$artisan->requirements[11]->item->id}} {{$artisan->requirements[11]->quantity}} {{$artisan->requirements[11]->quality->value}}/1/6" #!String
    Crafts Room/13: "{!! trim($springfo->translation) !!}/{{$springfo->prize->type}} {{$springfo->prize->item->id}} {{$springfo->prize->quantity}}/{{$springfo->requirements[0]->item->id}} {{$springfo->requirements[0]->quantity}} {{$springfo->requirements[0]->quality->value}} {{$springfo->requirements[1]->item->id}} {{$springfo->requirements[1]->quantity}} {{$springfo->requirements[1]->quality->value}} {{$springfo->requirements[2]->item->id}} {{$springfo->requirements[2]->quantity}} {{$springfo->requirements[2]->quality->value}} {{$springfo->requirements[3]->item->id}} {{$springfo->requirements[3]->quantity}} {{$springfo->requirements[3]->quality->value}}/0" #!String
    Crafts Room/14: "{!! trim($summerfo->translation) !!}/{{$summerfo->prize->type}} {{$summerfo->prize->item->id}} {{$summerfo->prize->quantity}}/{{$summerfo->requirements[0]->item->id}} {{$summerfo->requirements[0]->quantity}} {{$summerfo->requirements[0]->quality->value}} {{$summerfo->requirements[1]->item->id}} {{$summerfo->requirements[1]->quantity}} {{$summerfo->requirements[1]->quality->value}} {{$summerfo->requirements[2]->item->id}} {{$summerfo->requirements[2]->quantity}} {{$summerfo->requirements[2]->quality->value}}/3" #!String
    Crafts Room/15: "{!! trim($fallfo->translation) !!}/{{$fallfo->prize->type}} {{$fallfo->prize->item->id}} {{$fallfo->prize->quantity}}/{{$fallfo->requirements[0]->item->id}} {{$fallfo->requirements[0]->quantity}} {{$fallfo->requirements[0]->quality->value}} {{$fallfo->requirements[1]->item->id}} {{$fallfo->requirements[1]->quantity}} {{$fallfo->requirements[1]->quality->value}} {{$fallfo->requirements[2]->item->id}} {{$fallfo->requirements[2]->quantity}} {{$fallfo->requirements[2]->quality->value}} {{$fallfo->requirements[3]->item->id}} {{$fallfo->requirements[3]->quantity}} {{$fallfo->requirements[3]->quality->value}}/2" #!String
    Crafts Room/16: "{!! trim($winterfo->translation) !!}/{{$winterfo->prize->type}} {{$winterfo->prize->item->id}} {{$winterfo->prize->quantity}}/{{$winterfo->requirements[0]->item->id}} {{$winterfo->requirements[0]->quantity}} {{$winterfo->requirements[0]->quality->value}} {{$winterfo->requirements[1]->item->id}} {{$winterfo->requirements[1]->quantity}} {{$winterfo->requirements[1]->quality->value}} {{$winterfo->requirements[2]->item->id}} {{$winterfo->requirements[2]->quantity}} {{$winterfo->requirements[2]->quality->value}} {{$winterfo->requirements[3]->item->id}} {{$winterfo->requirements[3]->quantity}} {{$winterfo->requirements[3]->quality->value}}/6" #!String
    Crafts Room/17: "{!! trim($construction->translation) !!}/{{$construction->prize->type}} {{$construction->prize->item->id}} {{$construction->prize->quantity}}/{{$construction->requirements[0]->item->id}} {{$construction->requirements[0]->quantity}} {{$construction->requirements[0]->quality->value}} {{$construction->requirements[1]->item->id}} {{$construction->requirements[1]->quantity}} {{$construction->requirements[1]->quality->value}} {{$construction->requirements[2]->item->id}} {{$construction->requirements[2]->quantity}} {{$construction->requirements[2]->quality->value}} {{$construction->requirements[3]->item->id}} {{$construction->requirements[3]->quantity}} {{$construction->requirements[3]->quality->value}}/4" #!String
    Crafts Room/19: "{!! trim($exotic->translation) !!}/{{$exotic->prize->type}} {{$exotic->prize->item->id}} {{$exotic->prize->quantity}}/{{$exotic->requirements[0]->item->id}} {{$exotic->requirements[0]->quantity}} {{$exotic->requirements[0]->quality->value}} {{$exotic->requirements[1]->item->id}} {{$exotic->requirements[1]->quantity}} {{$exotic->requirements[1]->quality->value}} {{$exotic->requirements[2]->item->id}} {{$exotic->requirements[2]->quantity}} {{$exotic->requirements[2]->quality->value}} {{$exotic->requirements[3]->item->id}} {{$exotic->requirements[3]->quantity}} {{$exotic->requirements[3]->quality->value}} {{$exotic->requirements[4]->item->id}} {{$exotic->requirements[4]->quantity}} {{$exotic->requirements[4]->quality->value}} {{$exotic->requirements[5]->item->id}} {{$exotic->requirements[5]->quantity}} {{$exotic->requirements[5]->quality->value}} {{$exotic->requirements[6]->item->id}} {{$exotic->requirements[6]->quantity}} {{$exotic->requirements[6]->quality->value}} {{$exotic->requirements[7]->item->id}} {{$exotic->requirements[7]->quantity}} {{$exotic->requirements[7]->quality->value}} {{$exotic->requirements[8]->item->id}} {{$exotic->requirements[8]->quantity}} {{$exotic->requirements[8]->quality->value}}/1/5" #!String
    Fish Tank/6: "{!! trim($river->translation) !!}/{{$river->prize->type}} {{$river->prize->item->id}} {{$river->prize->quantity}}/{{$river->requirements[0]->item->id}} {{$river->requirements[0]->quantity}} {{$river->requirements[0]->quality->value}} {{$river->requirements[1]->item->id}} {{$river->requirements[1]->quantity}} {{$river->requirements[1]->quality->value}} {{$river->requirements[2]->item->id}} {{$river->requirements[2]->quantity}} {{$river->requirements[2]->quality->value}} {{$river->requirements[3]->item->id}} {{$river->requirements[3]->quantity}} {{$river->requirements[3]->quality->value}}/6" #!String
    Fish Tank/7: "{!! trim($lake->translation) !!}/{{$lake->prize->type}} {{$lake->prize->item->id}} {{$lake->prize->quantity}}/{{$lake->requirements[0]->item->id}} {{$lake->requirements[0]->quantity}} {{$lake->requirements[0]->quality->value}} {{$lake->requirements[1]->item->id}} {{$lake->requirements[1]->quantity}} {{$lake->requirements[1]->quality->value}} {{$lake->requirements[2]->item->id}} {{$lake->requirements[2]->quantity}} {{$lake->requirements[2]->quality->value}} {{$lake->requirements[3]->item->id}} {{$lake->requirements[3]->quantity}} {{$lake->requirements[3]->quality->value}}/0" #!String
    Fish Tank/8: "{!! trim($ocean->translation) !!}/{{$ocean->prize->type}} {{$ocean->prize->item->id}} {{$ocean->prize->quantity}}/{{$ocean->requirements[0]->item->id}} {{$ocean->requirements[0]->quantity}} {{$ocean->requirements[0]->quality->value}} {{$ocean->requirements[1]->item->id}} {{$ocean->requirements[1]->quantity}} {{$ocean->requirements[1]->quality->value}} {{$ocean->requirements[2]->item->id}} {{$ocean->requirements[2]->quantity}} {{$ocean->requirements[2]->quality->value}} {{$ocean->requirements[3]->item->id}} {{$ocean->requirements[3]->quantity}} {{$ocean->requirements[3]->quality->value}}/5" #!String
    Fish Tank/9: "{!! trim($night->translation) !!}/{{$night->prize->type}} {{$night->prize->item->id}} {{$night->prize->quantity}}/{{$night->requirements[0]->item->id}} {{$night->requirements[0]->quantity}} {{$night->requirements[0]->quality->value}} {{$night->requirements[1]->item->id}} {{$night->requirements[1]->quantity}} {{$night->requirements[1]->quality->value}} {{$night->requirements[2]->item->id}} {{$night->requirements[2]->quantity}} {{$night->requirements[2]->quality->value}}/1" #!String
    Fish Tank/10: "{!! trim($specialty->translation) !!}/{{$specialty->prize->type}} {{$specialty->prize->item->id}} {{$specialty->prize->quantity}}/{{$specialty->requirements[0]->item->id}} {{$specialty->requirements[0]->quantity}} {{$specialty->requirements[0]->quality->value}} {{$specialty->requirements[1]->item->id}} {{$specialty->requirements[1]->quantity}} {{$specialty->requirements[1]->quality->value}} {{$specialty->requirements[2]->item->id}} {{$specialty->requirements[2]->quantity}} {{$specialty->requirements[2]->quality->value}} {{$specialty->requirements[3]->item->id}} {{$specialty->requirements[3]->quantity}} {{$specialty->requirements[3]->quality->value}}/4" #!String
    Fish Tank/11: "{!! trim($crab->translation) !!}/{{$crab->prize->type}} {{$crab->prize->item->id}} {{$crab->prize->quantity}}/{{$crab->requirements[0]->item->id}} {{$crab->requirements[0]->quantity}} {{$crab->requirements[0]->quality->value}} {{$crab->requirements[1]->item->id}} {{$crab->requirements[1]->quantity}} {{$crab->requirements[1]->quality->value}} {{$crab->requirements[2]->item->id}} {{$crab->requirements[2]->quantity}} {{$crab->requirements[2]->quality->value}} {{$crab->requirements[3]->item->id}} {{$crab->requirements[3]->quantity}} {{$crab->requirements[3]->quality->value}} {{$crab->requirements[4]->item->id}} {{$crab->requirements[4]->quantity}} {{$crab->requirements[4]->quality->value}} {{$crab->requirements[5]->item->id}} {{$crab->requirements[5]->quantity}} {{$crab->requirements[5]->quality->value}} {{$crab->requirements[6]->item->id}} {{$crab->requirements[6]->quantity}} {{$crab->requirements[6]->quality->value}} {{$crab->requirements[7]->item->id}} {{$crab->requirements[7]->quantity}} {{$crab->requirements[7]->quality->value}} {{$crab->requirements[8]->item->id}} {{$crab->requirements[8]->quantity}} {{$crab->requirements[8]->quality->value}} {{$crab->requirements[9]->item->id}} {{$crab->requirements[9]->quantity}} {{$crab->requirements[9]->quality->value}}/1/5" #!String
    Boiler Room/20: "{!! trim($blacksmith->translation) !!}/{{$blacksmith->prize->type}} {{$blacksmith->prize->item->id}} {{$blacksmith->prize->quantity}}/{{$blacksmith->requirements[0]->item->id}} {{$blacksmith->requirements[0]->quantity}} {{$blacksmith->requirements[0]->quality->value}} {{$blacksmith->requirements[1]->item->id}} {{$blacksmith->requirements[1]->quantity}} {{$blacksmith->requirements[1]->quality->value}} {{$blacksmith->requirements[2]->item->id}} {{$blacksmith->requirements[2]->quantity}} {{$blacksmith->requirements[2]->quality->value}}/2" #!String
    Boiler Room/21: "{!! trim($geologist->translation) !!}/{{$geologist->prize->type}} {{$geologist->prize->item->id}} {{$geologist->prize->quantity}}/{{$geologist->requirements[0]->item->id}} {{$geologist->requirements[0]->quantity}} {{$geologist->requirements[0]->quality->value}} {{$geologist->requirements[1]->item->id}} {{$geologist->requirements[1]->quantity}} {{$geologist->requirements[1]->quality->value}} {{$geologist->requirements[2]->item->id}} {{$geologist->requirements[2]->quantity}} {{$geologist->requirements[2]->quality->value}} {{$geologist->requirements[3]->item->id}} {{$geologist->requirements[3]->quantity}} {{$geologist->requirements[3]->quality->value}}/1" #!String
    Boiler Room/22: "{!! trim($adventurer->translation) !!}/{{$adventurer->prize->type}} {{$adventurer->prize->item->id}} {{$adventurer->prize->quantity}}/{{$adventurer->requirements[0]->item->id}} {{$adventurer->requirements[0]->quantity}} {{$adventurer->requirements[0]->quality->value}} {{$adventurer->requirements[1]->item->id}} {{$adventurer->requirements[1]->quantity}} {{$adventurer->requirements[1]->quality->value}} {{$adventurer->requirements[2]->item->id}} {{$adventurer->requirements[2]->quantity}} {{$adventurer->requirements[2]->quality->value}} {{$adventurer->requirements[3]->item->id}} {{$adventurer->requirements[3]->quantity}} {{$adventurer->requirements[3]->quality->value}}/1/2" #!String
    Vault/23: "{!! trim($vaultSmall->translation) !!}/{{$vaultSmall->prize->type}} {{$vaultSmall->prize->item->id}} {{$vaultSmall->prize->quantity}}/-1 {{$vaultSmall->money->value}} {{$vaultSmall->money->value}}/4" #!String
    Vault/24: "{!! trim($vaultMedium->translation) !!}/{{$vaultMedium->prize->type}} {{$vaultMedium->prize->item->id}} {{$vaultMedium->prize->quantity}}/-1 {{$vaultMedium->money->value}} {{$vaultMedium->money->value}}/2" #!String
    Vault/25: "{!! trim($vaultBig->translation) !!}/{{$vaultBig->prize->type}} {{$vaultBig->prize->item->id}} {{$vaultBig->prize->quantity}}/-1 {{$vaultBig->money->value}} {{$vaultBig->money->value}}/3" #!String
    Vault/26: "{!! trim($vaultLarge->translation) !!}/{{$vaultLarge->prize->type}} {{$vaultLarge->prize->item->id}} {{$vaultLarge->prize->quantity}}/-1 {{$vaultLarge->money->value}} {{$vaultLarge->money->value}}/1" #!String
    Bulletin Board/31: "{!! trim($chef->translation) !!}/{{$chef->prize->type}} {{$chef->prize->item->id}} {{$chef->prize->quantity}}/{{$chef->requirements[0]->item->id}} {{$chef->requirements[0]->quantity}} {{$chef->requirements[0]->quality->value}} {{$chef->requirements[1]->item->id}} {{$chef->requirements[1]->quantity}} {{$chef->requirements[1]->quality->value}} {{$chef->requirements[2]->item->id}} {{$chef->requirements[2]->quantity}} {{$chef->requirements[2]->quality->value}} {{$chef->requirements[3]->item->id}} {{$chef->requirements[3]->quantity}} {{$chef->requirements[3]->quality->value}} {{$chef->requirements[4]->item->id}} {{$chef->requirements[4]->quantity}} {{$chef->requirements[4]->quality->value}} {{$chef->requirements[5]->item->id}} {{$chef->requirements[5]->quantity}} {{$chef->requirements[5]->quality->value}}/4" #!String
    Bulletin Board/32: "{!! trim($field->translation) !!}/{{$field->prize->type}} {{$field->prize->item->id}} {{$field->prize->quantity}}/{{$field->requirements[0]->item->id}} {{$field->requirements[0]->quantity}} {{$field->requirements[0]->quality->value}} {{$field->requirements[1]->item->id}} {{$field->requirements[1]->quantity}} {{$field->requirements[1]->quality->value}} {{$field->requirements[2]->item->id}} {{$field->requirements[2]->quantity}} {{$field->requirements[2]->quality->value}} {{$field->requirements[3]->item->id}} {{$field->requirements[3]->quantity}} {{$field->requirements[3]->quality->value}}/5" #!String
    Bulletin Board/33: "{!! trim($enchanter->translation) !!}/{{$enchanter->prize->type}} {{$enchanter->prize->item->id}} {{$enchanter->prize->quantity}}/{{$enchanter->requirements[0]->item->id}} {{$enchanter->requirements[0]->quantity}} {{$enchanter->requirements[0]->quality->value}} {{$enchanter->requirements[1]->item->id}} {{$enchanter->requirements[1]->quantity}} {{$enchanter->requirements[1]->quality->value}} {{$enchanter->requirements[2]->item->id}} {{$enchanter->requirements[2]->quantity}} {{$enchanter->requirements[2]->quality->value}} {{$enchanter->requirements[3]->item->id}} {{$enchanter->requirements[3]->quantity}} {{$enchanter->requirements[3]->quality->value}}/1" #!String
    Bulletin Board/34: "{!! trim($dye->translation) !!}/{{$dye->prize->type}} {{$dye->prize->item->id}} {{$dye->prize->quantity}}/{{$dye->requirements[0]->item->id}} {{$dye->requirements[0]->quantity}} {{$dye->requirements[0]->quality->value}} {{$dye->requirements[1]->item->id}} {{$dye->requirements[1]->quantity}} {{$dye->requirements[1]->quality->value}} {{$dye->requirements[2]->item->id}} {{$dye->requirements[2]->quantity}} {{$dye->requirements[2]->quality->value}} {{$dye->requirements[3]->item->id}} {{$dye->requirements[3]->quantity}} {{$dye->requirements[3]->quality->value}} {{$dye->requirements[4]->item->id}} {{$dye->requirements[4]->quantity}} {{$dye->requirements[4]->quality->value}} {{$dye->requirements[5]->item->id}} {{$dye->requirements[5]->quantity}} {{$dye->requirements[5]->quality->value}}/6" #!String
    Bulletin Board/35: "{!! trim($fodder->translation) !!}/{{$fodder->prize->type}} {{$fodder->prize->item->id}} {{$fodder->prize->quantity}}/{{$fodder->requirements[0]->item->id}} {{$fodder->requirements[0]->quantity}} {{$fodder->requirements[0]->quality->value}} {{$fodder->requirements[1]->item->id}} {{$fodder->requirements[1]->quantity}} {{$fodder->requirements[1]->quality->value}} {{$fodder->requirements[2]->item->id}} {{$fodder->requirements[2]->quantity}} {{$fodder->requirements[2]->quality->value}}/3" #!String